// Image generation prompts for all 78 tarot cards
const STYLE_SUFFIX = "Style of Alex Aliume and Chesley Bonestell, digital painting, rich deep purples and blues with golden cosmic dust, dramatic lighting, highly detailed, 8k.";

// Major Arcana Prompts (0-21)
const MAJOR_ARCANA_PROMPTS = [
  { name: "The Fool", number: 0, prompt: "An ethereal young figure with shimmering cosmic patterns woven into tattered flowing robes, standing at the edge of a swirling dark fantasy nebula cliff. Eyes reflect distant galaxies, a star-studded path stretches into the unknown void. A small glowing astral dog companion leaps playfully beside them. Ancient cosmic ruins float in the background. " + STYLE_SUFFIX },
  { name: "The Magician", number: 1, prompt: "A powerful cosmic sorcerer figure channeling swirling nebula energy between raised hands, one pointing to distant galaxies above, one to a dark planetary surface below. Ethereal glowing tools float around them - a luminous wand, crystalline cup, spectral sword, and golden pentacle. An infinity symbol of stars burns above their head. Ancient cosmic temple ruins in background. " + STYLE_SUFFIX },
  { name: "The High Priestess", number: 2, prompt: "A mysterious veiled feminine figure seated on a throne between two towering cosmic pillars - one of dark matter, one of pure starlight. She holds an ancient glowing scroll of celestial secrets. A luminous crescent moon crown adorns her head. Behind her, a veil of shimmering nebula conceals deeper mysteries. Dark reflective waters at her feet mirror distant galaxies. " + STYLE_SUFFIX },
  { name: "The Empress", number: 3, prompt: "A radiant cosmic goddess reclining on a throne of living stardust and flowering nebulae. She wears a crown of twelve stars and robes that flow into rivers of galaxies. Lush bioluminescent cosmic gardens bloom around her with ethereal plants and glowing fruits. A heart-shaped shield of golden light rests beside her. Planets orbit gently in the background like celestial children. " + STYLE_SUFFIX },
  { name: "The Emperor", number: 4, prompt: "A powerful cosmic ruler seated on a massive throne carved from asteroid rock and ancient cosmic metals, adorned with ram skull motifs made of stars. He wears armor forged from compressed starlight and holds an ankh scepter crackling with nebula energy. His stern gaze surveys a vast empire of ordered star systems. Geometric sacred patterns of constellations form behind him. " + STYLE_SUFFIX },
  { name: "The Hierophant", number: 5, prompt: "An ancient cosmic pope figure seated between two pillars of crystallized wisdom in a vast cathedral of stars. He wears elaborate robes embroidered with sacred geometries and constellations, a triple crown of orbiting moons. One hand raised in blessing channels divine light, the other holds a triple cross staff of intertwined galaxies. Two robed disciples kneel before him on a floor of ancient star maps. " + STYLE_SUFFIX },
  { name: "The Lovers", number: 6, prompt: "Two ethereal figures - one masculine, one feminine - floating in an embrace within a heart-shaped nebula, their forms partially merging into swirling cosmic energy. Above them, a radiant angelic being made of pure starlight blesses their union with outstretched wings of aurora. Below, the tree of life and tree of knowledge grow from a shared cosmic garden. Twin suns illuminate the scene. " + STYLE_SUFFIX },
  { name: "The Chariot", number: 7, prompt: "A triumphant cosmic warrior standing in a magnificent chariot made of meteoric iron and crystallized starlight, pulled by two powerful sphinx creatures - one of dark matter, one of pure light. The warrior wears armor decorated with celestial symbols and holds the reins of pure energy. A canopy of stars forms above. The chariot races across a bridge of light between galaxies, leaving trails of cosmic dust. " + STYLE_SUFFIX },
  { name: "Strength", number: 8, prompt: "A serene feminine figure gently closing the jaws of a massive cosmic lion made of swirling nebulae and burning stars. Her touch radiates calm golden light that tames the beast's fierce energy. She wears flowing robes of soft starlight, an infinity symbol of gentle stars above her head. The lion's mane flows into rivers of galaxies. A peaceful cosmic meadow of glowing flowers surrounds them. " + STYLE_SUFFIX },
  { name: "The Hermit", number: 9, prompt: "An ancient hooded sage standing alone atop a desolate cosmic mountain peak, holding a lantern containing a trapped star that illuminates the infinite darkness. His weathered robes are woven from the fabric of space itself. A long staff of crystallized time supports his contemplation. Below, endless void stretches with distant galaxies. The figure gazes inward while lighting the way for seekers far below. " + STYLE_SUFFIX },
  { name: "Wheel of Fortune", number: 10, prompt: "A massive cosmic wheel spinning in the center of the universe, made of interlocking galaxies and orbital rings inscribed with alchemical symbols. Mysterious creatures ride the wheel - a sphinx of starlight at the top, a serpent of dark matter descending, a jackal-headed figure of nebulae rising. The four corners hold winged cosmic beings representing the fixed signs. Lightning of pure creation energy crackles around the wheel. " + STYLE_SUFFIX },
  { name: "Justice", number: 11, prompt: "A blindfolded cosmic judge seated on a throne of balanced scales between order and chaos. In one hand, a sword of pure crystallized truth cuts through nebulae. In the other, perfectly balanced scales weigh galaxies of light against galaxies of shadow. The figure wears robes of mathematical precision, sacred geometry forming the patterns. Twin pillars of cosmic law frame the scene. A level horizon of stars stretches infinitely behind. " + STYLE_SUFFIX },
  { name: "The Hanged Man", number: 12, prompt: "A serene figure suspended upside-down from a cosmic tree that grows from nothing into everything, roots in stars, branches in void. The figure hangs by one ankle, other leg crossed, arms behind back forming a triangle, surrounded by a halo of enlightenment. Their peaceful face shows transcendence, not suffering. Galaxies swirl differently from this inverted perspective. Golden light emanates from within their being. " + STYLE_SUFFIX },
  { name: "Death", number: 13, prompt: "A skeletal cosmic reaper in flowing robes of pure void, riding a pale horse made of dying stars across a battlefield where old galaxies crumble and new ones begin to form. The figure carries a black banner emblazoned with a white rose of rebirth. Before them, kings and paupers of light equally fall and transform. Behind them, dawn breaks over a new universe being born from the ashes. " + STYLE_SUFFIX },
  { name: "Temperance", number: 14, prompt: "A radiant angelic figure with iridescent wings of aurora light standing with one foot in a pool of liquid starlight, one on solid cosmic ground. They pour luminous essence between two chalices in an eternal flow that never spills - liquid light and liquid shadow mixing into perfect balance. A path of stepping stones leads to distant mountains where a crown of light awaits. Irises of pure light bloom at their feet. " + STYLE_SUFFIX },
  { name: "The Devil", number: 15, prompt: "A massive horned shadow entity perched on a cubic black hole throne, half goat, half bat, with hypnotic spiral galaxies for eyes. Chains of dark matter loosely bind two smaller humanoid figures to the throne - chains they could easily remove but choose not to. An inverted pentagram of dying stars burns above. The creature holds a torch pointing downward, its dark flame consuming light. Tempting treasures of corrupted gold float nearby. " + STYLE_SUFFIX },
  { name: "The Tower", number: 16, prompt: "A colossal cosmic tower built from crystallized false beliefs shatters as a bolt of divine lightning from a supernova strikes its crown. Figures of light tumble through space as the structure crumbles. The crown - a symbol of material achievement - is blown off and falls into the void. Flames of purifying cosmic fire consume the old order. Through the destruction, a new dawn of clarity breaks on the horizon. Debris transforms into seeds of new creation. " + STYLE_SUFFIX },
  { name: "The Star", number: 17, prompt: "A serene nude figure kneels at the edge of a cosmic pool, pouring starlight from two vessels - one into the water of the subconscious, one onto the land of the material world. Above her, one great eight-pointed star of hope blazes surrounded by seven smaller stars representing the chakras. Her form glows with inner light. The landscape is peaceful, with an ibis of wisdom perched nearby and cosmic flowers blooming. Healing energy radiates everywhere. " + STYLE_SUFFIX },
  { name: "The Moon", number: 18, prompt: "A haunting cosmic landscape under a massive moon with a mysterious face, dripping luminescent dew into a dark reflective pool. A winding path leads between two ominous towers of shadow into unknown darkness. A wolf and a domesticated dog howl at the moon - the wild and tamed aspects of mind. A cosmic crayfish emerges from the primordial waters of the subconscious. Everything shimmers with deceptive beauty and hidden danger. Illusions dance in the moonlight. " + STYLE_SUFFIX },
  { name: "The Sun", number: 19, prompt: "A radiant cosmic sun with a benevolent face blazes gloriously, its rays reaching across the universe bringing life and joy. Below, a joyful child of light rides a white horse made of pure starlight through a garden of massive cosmic sunflowers. A red banner of vitality waves triumphantly. Everything is illuminated - no shadows can hide here. The child's innocence and joy are infectious. Golden light bathes every surface in warmth and clarity. " + STYLE_SUFFIX },
  { name: "Judgement", number: 20, prompt: "A colossal cosmic angel emerges from swirling clouds of nebulae, blowing a trumpet that sends waves of awakening energy across the universe. Below, figures of light rise from cosmic tombs and crystalline coffins, arms raised in resurrection and liberation. Families reunite across the barriers of time and space. The trumpet's call echoes through dimensions, awakening souls to their higher purpose. A cross of balanced cosmic energy marks the banner of transformation. " + STYLE_SUFFIX },
  { name: "The World", number: 21, prompt: "A dancing cosmic figure floats within a great wreath made of intertwined galaxies, celebrating the completion of the universal journey. They hold two wands of mastery, their form expressing perfect integration and wholeness. In the four corners, the four cosmic creatures watch - lion of fire, bull of earth, eagle of water, angel of air - representing mastered elements and fixed signs. The entire universe seems to dance in harmony. A sense of arrival and fulfillment pervades everything. " + STYLE_SUFFIX }
];

// Minor Arcana - Wands (Fire element - oranges, reds, golds)
const WANDS_STYLE = "Style of Alex Aliume and Chesley Bonestell, digital painting, rich fiery oranges and reds with golden cosmic flames, dramatic lighting, highly detailed, 8k.";
const WANDS_PROMPTS = [
  { name: "Ace of Wands", number: 22, prompt: "A single magnificent cosmic wand made of crystallized fire and starlight emerges from a nebula cloud, bursting with creative energy. Golden flames spiral around it, seeds of new galaxies scatter from its tip. A hand of pure light grasps it from the void. The background shows the birth of new stars. " + WANDS_STYLE },
  { name: "Two of Wands", number: 23, prompt: "A cosmic figure stands on a balcony of floating asteroids, holding one flaming wand while another rests nearby. They gaze across vast galaxies, contemplating infinite possibilities. A small glowing globe of mapped star systems rests in their palm. The universe stretches before them like an uncharted map. " + WANDS_STYLE },
  { name: "Three of Wands", number: 24, prompt: "A figure of starlight stands with three blazing wands planted before them, watching cosmic ships of light sail between galaxies. They've sent their creations into the universe and await their return. Golden trade routes of energy connect distant star systems. Expansion and growth permeate the scene. " + WANDS_STYLE },
  { name: "Four of Wands", number: 25, prompt: "Four cosmic wands form the corners of a celestial gateway decorated with wreaths of nebula flowers. Joyful figures of light dance beneath it in celebration. A cosmic castle of crystallized fire rises in the background. The scene radiates warmth, welcome, and community. " + WANDS_STYLE },
  { name: "Five of Wands", number: 26, prompt: "Five figures of different cosmic energies clash their flaming wands in a chaotic but non-lethal contest. Sparks of creative conflict fly everywhere. Each fighter has a unique style. The ground beneath them is scorched with the marks of their competition. Creative tension fills the air. " + WANDS_STYLE },
  { name: "Six of Wands", number: 27, prompt: "A triumphant cosmic warrior rides a horse of living flame, holding a wand high with a victory wreath of golden light. Five other wands rise around them as a crowd of cosmic beings celebrates. The hero's armor gleams with the fire of achievement. Glory and recognition radiate from the scene. " + WANDS_STYLE },
  { name: "Seven of Wands", number: 28, prompt: "A lone figure stands atop a rocky cosmic cliff, defending their position with a single flaming wand against six wands rising from below. Their stance is fierce and determined. The high ground gives them advantage. The battle is about maintaining hard-won success. " + WANDS_STYLE },
  { name: "Eight of Wands", number: 29, prompt: "Eight blazing wands streak across the cosmic sky like meteors, all aimed at the same distant destination. They travel with incredible speed and purpose. The landscape below blurs with their passage. Energy, momentum, and swift action define the image. " + WANDS_STYLE },
  { name: "Nine of Wands", number: 30, prompt: "A weary but unbowed cosmic warrior stands guard with a single wand, eight others forming a defensive wall behind them. Bandaged but resilient, they've weathered many battles. Their eyes remain vigilant. Persistence and determination despite exhaustion. " + WANDS_STYLE },
  { name: "Ten of Wands", number: 31, prompt: "A figure struggles to carry ten heavy flaming wands toward a distant cosmic city of light. The burden is almost too much, but they press forward. Their back is bent but not broken. The destination promises rest and reward for their labors. " + WANDS_STYLE },
  { name: "Page of Wands", number: 32, prompt: "A young cosmic messenger examines a single flaming wand with wonder and excitement. Their clothes shimmer with the promise of adventure. A salamander of living fire coils at their feet. The vast universe beckons with endless possibilities. Enthusiasm and discovery radiate from them. " + WANDS_STYLE },
  { name: "Knight of Wands", number: 33, prompt: "A dashing cosmic knight charges forward on a rearing horse of pure flame, brandishing a blazing wand. Their cloak streams behind them like a comet tail. Salamanders of fire accompany their charge. Passion, adventure, and impulsive energy define them. " + WANDS_STYLE },
  { name: "Queen of Wands", number: 34, prompt: "A magnificent cosmic queen sits on a throne carved from volcanic rock and decorated with living flames. She holds a flowering wand and a sunflower of golden light. A loyal lion of fire rests at her feet. She radiates confidence, warmth, and magnetic charisma. " + WANDS_STYLE },
  { name: "King of Wands", number: 35, prompt: "A powerful cosmic king sits on a throne of eternal flame, holding a living wand that sprouts with new fire. His crown blazes with creative authority. A salamander of cosmic fire circles the throne. He embodies visionary leadership and entrepreneurial spirit. " + WANDS_STYLE }
];

// Minor Arcana - Cups (Water element - blues, teals, silvers)
const CUPS_STYLE = "Style of Alex Aliume and Chesley Bonestell, digital painting, rich ocean blues and teals with silver moonlight reflections, ethereal lighting, highly detailed, 8k.";
const CUPS_PROMPTS = [
  { name: "Ace of Cups", number: 36, prompt: "A magnificent chalice of crystallized moonlight overflows with cascading liquid starlight. A dove of pure light descends toward it. Five streams pour from the cup, representing the five senses. Lotus flowers of emotion bloom on the cosmic waters below. Love and spiritual abundance overflow. " + CUPS_STYLE },
  { name: "Two of Cups", number: 37, prompt: "Two figures of complementary cosmic energy face each other, each holding a cup that flows into the other. Above them, a caduceus of intertwined cosmic serpents crowned with a winged lion head. Their union creates a third energy between them. Partnership and mutual attraction. " + CUPS_STYLE },
  { name: "Three of Cups", number: 38, prompt: "Three joyful cosmic maidens dance in a circle, raising their cups high in celebration. Fruits of emotional abundance surround them. Their laughter creates ripples in the cosmic waters. A harvest of feelings surrounds them. Friendship, community, and shared joy. " + CUPS_STYLE },
  { name: "Four of Cups", number: 39, prompt: "A figure sits beneath a cosmic tree, arms crossed, looking discontentedly at three cups before them. A fourth cup is offered by a mysterious hand from a cloud, but they don't notice. Emotional apathy and missed opportunities. Contemplation bordering on withdrawal. " + CUPS_STYLE },
  { name: "Five of Cups", number: 40, prompt: "A cloaked figure in black stands mourning over three spilled cups, their contents flowing away. Behind them, two cups remain standing but unnoticed. A bridge leads to a distant sanctuary across dark waters. Grief and focusing on loss while blessings remain. " + CUPS_STYLE },
  { name: "Six of Cups", number: 41, prompt: "In a garden of cosmic memory, a young figure offers a cup filled with a glowing flower to another child. Six cups filled with blooming nostalgia surround them. The scene has a dreamy, innocent quality. Old houses of crystallized memory rise nearby. Nostalgia and simple joys of the past. " + CUPS_STYLE },
  { name: "Seven of Cups", number: 42, prompt: "A figure gazes at seven cups floating in clouds of illusion. Each cup contains a different vision - a castle, jewels, a wreath, a dragon, treasure, a glowing figure, a serpent. All are ephemeral and dreamlike. Fantasy, choices, and wishful thinking. " + CUPS_STYLE },
  { name: "Eight of Cups", number: 43, prompt: "A cloaked figure walks away from eight carefully stacked cups toward distant cosmic mountains under an eclipse. The moon is partial, showing this is incomplete. They seek something more meaningful. Departure and the courage to walk away. " + CUPS_STYLE },
  { name: "Nine of Cups", number: 44, prompt: "A satisfied figure sits with arms crossed before a curved display of nine golden cups. Their expression is contentment itself. A rich blue curtain frames the scene. Material and emotional wishes have been fulfilled. The wish card - satisfaction and abundance. " + CUPS_STYLE },
  { name: "Ten of Cups", number: 45, prompt: "A cosmic family - two adults and two children - stand with arms raised in joy as a rainbow arc of ten cups appears in the sky above their idyllic home. Pure emotional fulfillment and lasting happiness. The ultimate emotional achievement. " + CUPS_STYLE },
  { name: "Page of Cups", number: 46, prompt: "A dreamy young figure in flowing cosmic robes looks with surprise at a fish emerging from their cup, offering a message. Their outfit is decorated with lotus flowers. They stand at the edge of cosmic waters. Imagination, intuition, and unexpected emotions. " + CUPS_STYLE },
  { name: "Knight of Cups", number: 47, prompt: "A graceful cosmic knight rides slowly on a white horse, holding a cup before them like a holy offering. Their armor and helmet are decorated with wings and fish. A river of stars flows nearby. Romance, charm, and following the heart. " + CUPS_STYLE },
  { name: "Queen of Cups", number: 48, prompt: "A serene cosmic queen sits on a throne at the edge of the celestial sea, holding an ornate closed cup she alone can see into. Sea spirits attend her. Her throne is decorated with mermaids and cosmic fish. Deep intuition and emotional depth. " + CUPS_STYLE },
  { name: "King of Cups", number: 49, prompt: "A calm cosmic king sits on a throne amid turbulent celestial waters, yet remains stable. He holds a cup in one hand, a scepter in the other. A fish leaps behind him, a ship sails steadily. Emotional balance and mature compassion. " + CUPS_STYLE }
];

// Minor Arcana - Swords (Air element - silvers, whites, pale blues)
const SWORDS_STYLE = "Style of Alex Aliume and Chesley Bonestell, digital painting, sharp silvers and steel blues with crisp white lightning, intense dramatic lighting, highly detailed, 8k.";
const SWORDS_PROMPTS = [
  { name: "Ace of Swords", number: 50, prompt: "A mighty sword of pure crystallized thought pierces through cosmic clouds, a crown of victory resting on its tip with olive and palm branches. The double-edged blade gleams with the power of truth. Mountains of mental clarity rise in the distance. Pure intellectual power and breakthrough. " + SWORDS_STYLE },
  { name: "Two of Swords", number: 51, prompt: "A blindfolded figure in white sits before a cosmic sea, holding two crossed swords in perfect balance. A crescent moon illuminates the scene. They refuse to see what must be confronted. A stalemate of the mind. Indecision and blocked emotions. " + SWORDS_STYLE },
  { name: "Three of Swords", number: 52, prompt: "Three swords pierce a floating heart amid a cosmic storm of rain and tears. Dark clouds swirl with grief. Yet the heart glows faintly, suggesting it can heal. The pain is necessary for growth. Heartbreak, sorrow, but also catharsis. " + SWORDS_STYLE },
  { name: "Four of Swords", number: 53, prompt: "A knight lies in repose on a cosmic tomb, hands clasped in prayer. Three swords hang above, one lies beneath them. A stained glass window of celestial light glows nearby. Rest from battle, meditation, and recovery. Contemplative withdrawal. " + SWORDS_STYLE },
  { name: "Five of Swords", number: 54, prompt: "A smirking figure holds three swords while two others lie on the ground. Two defeated figures walk away in the distance under stormy skies. The victory feels hollow. Winning at the cost of others. Conflict and hollow victory. " + SWORDS_STYLE },
  { name: "Six of Swords", number: 55, prompt: "A cloaked figure guides a boat carrying another shrouded passenger and six swords across troubled waters toward calmer seas. The water is choppy on one side, smooth on the other. Moving away from difficulty toward peace. Transition and recovery. " + SWORDS_STYLE },
  { name: "Seven of Swords", number: 56, prompt: "A figure sneaks away from a cosmic encampment carrying five swords, looking back craftily. Two swords remain planted in the ground. Their footsteps are light, their intent unclear. Strategy that borders on deception. Cunning and resourcefulness. " + SWORDS_STYLE },
  { name: "Eight of Swords", number: 57, prompt: "A blindfolded, bound figure stands surrounded by eight swords planted in the ground, though their bonds are loose. A cosmic castle rises in the distance. Water pools at their feet. They could escape if they tried. Self-imposed restriction and mental imprisonment. " + SWORDS_STYLE },
  { name: "Nine of Swords", number: 58, prompt: "A figure sits up in bed, head in hands in despair, while nine swords hang horizontally on the dark wall behind them. Their quilted blanket shows roses and astrological symbols. The night is darkest before dawn. Anxiety, nightmares, and mental anguish. " + SWORDS_STYLE },
  { name: "Ten of Swords", number: 59, prompt: "A figure lies face down on the cosmic ground with ten swords in their back. Yet dawn breaks golden on the horizon. The worst has happened, but a new day begins. Absolute ending, but also the promise of renewal. Rock bottom and release. " + SWORDS_STYLE },
  { name: "Page of Swords", number: 60, prompt: "A alert young figure stands on rocky cosmic ground, holding a sword upright with both hands. Their hair and clothes blow in a strong wind. Clouds swirl dramatically around them. They're ready for anything. Mental energy, curiosity, and vigilance. " + SWORDS_STYLE },
  { name: "Knight of Swords", number: 61, prompt: "A cosmic knight charges forward on a galloping white horse, sword raised high, cape flying. Storm clouds and cosmic winds surround them. They rush headlong into battle. Swift action, possibly too swift. Ambition and aggression. " + SWORDS_STYLE },
  { name: "Queen of Swords", number: 62, prompt: "A stern cosmic queen sits on a throne high in the clouds, holding a sword upright in one hand, the other extended in judgment. Her crown is of butterflies and sylphs. Birds fly nearby. She sees through all deception. Clear perception and direct truth. " + SWORDS_STYLE },
  { name: "King of Swords", number: 63, prompt: "A commanding cosmic king sits on a throne carved with sylphs and butterflies, holding a sword of authority. His expression is stern but fair. Clouds and geometric patterns surround him. He rules with intellect and ethical clarity. Mental authority and truth. " + SWORDS_STYLE }
];

// Minor Arcana - Pentacles (Earth element - greens, golds, browns)
const PENTACLES_STYLE = "Style of Alex Aliume and Chesley Bonestell, digital painting, rich emerald greens and earthy golds with warm abundant light, grounded atmosphere, highly detailed, 8k.";
const PENTACLES_PROMPTS = [
  { name: "Ace of Pentacles", number: 64, prompt: "A glowing hand emerges from cosmic clouds offering a massive golden pentacle. A garden of material abundance blooms below, with an archway of flowering cosmic vines leading to distant mountains. The path to prosperity opens. New financial or material opportunity. " + PENTACLES_STYLE },
  { name: "Two of Pentacles", number: 65, prompt: "A cosmic juggler dances while keeping two pentacles aloft, connected by an infinity ribbon. Ships ride high waves in the background. Their dance is joyful despite the challenge. Balance amid change. Adaptability and time management. " + PENTACLES_STYLE },
  { name: "Three of Pentacles", number: 66, prompt: "A craftsman works on a cosmic cathedral while a monk and noble review architectural plans together. Three pentacles are carved into an archway. Each person contributes their expertise. Teamwork, skill, and collaborative creation. " + PENTACLES_STYLE },
  { name: "Four of Pentacles", number: 67, prompt: "A figure sits in a cosmic city, clutching one pentacle tightly to their chest while balancing one on their head and two under their feet. Their expression is guarded. They have much but fear losing it. Security and conservation, but also attachment. " + PENTACLES_STYLE },
  { name: "Five of Pentacles", number: 68, prompt: "Two impoverished figures walk through a cosmic snowstorm past a glowing stained glass window with five pentacles. They seem unaware of the sanctuary offering help. Material hardship and spiritual poverty. The help exists if they'd only look. " + PENTACLES_STYLE },
  { name: "Six of Pentacles", number: 69, prompt: "A wealthy cosmic merchant holds balanced scales while distributing golden coins to those in need. Six pentacles are arranged around the scene. Generosity flows in proper measure. Giving and receiving in balance. Charity and fairness. " + PENTACLES_STYLE },
  { name: "Seven of Pentacles", number: 70, prompt: "A farmer leans on their hoe, contemplating a lush bush bearing seven golden pentacles. Their work has produced results, but they wonder if it's enough. Should they continue or try something new? Patience, assessment, and long-term investment. " + PENTACLES_STYLE },
  { name: "Eight of Pentacles", number: 71, prompt: "A dedicated craftsman diligently carves pentacles at their workbench. Six completed pentacles hang on display, they're working on the seventh, one awaits. A cosmic city rises in the distance. Skill development through dedication. Apprenticeship and mastery. " + PENTACLES_STYLE },
  { name: "Nine of Pentacles", number: 72, prompt: "An elegant figure stands in a lush cosmic garden filled with grapevines and golden pentacles. A hooded falcon rests on their gloved hand. A cosmic manor rises behind them. Self-sufficiency and refined abundance. Luxury earned through effort. " + PENTACLES_STYLE },
  { name: "Ten of Pentacles", number: 73, prompt: "A multi-generational cosmic family gathers in the courtyard of their ancestral home. Ten pentacles form the Tree of Life pattern. Dogs play at the elder's feet while children run past. Wealth, legacy, and establishment. Family prosperity. " + PENTACLES_STYLE },
  { name: "Page of Pentacles", number: 74, prompt: "A studious young figure stands in a flowering cosmic field, holding a single pentacle and gazing at it with focused attention. Their clothing is fine but practical. Mountains and forests of potential rise in the distance. Manifestation and study. " + PENTACLES_STYLE },
  { name: "Knight of Pentacles", number: 75, prompt: "A steadfast cosmic knight sits motionless on a heavy dark horse, holding a single pentacle. Unlike other knights, they don't rush. The landscape is carefully plowed and cultivated. Reliability, methodology, and steady progress. " + PENTACLES_STYLE },
  { name: "Queen of Pentacles", number: 76, prompt: "A nurturing cosmic queen sits on a throne decorated with fruit trees, goats, and abundance symbols, holding a golden pentacle in her lap. A rabbit hops nearby. Her garden is the most fertile in the cosmos. Practical nurturing and earthly abundance. " + PENTACLES_STYLE },
  { name: "King of Pentacles", number: 77, prompt: "A prosperous cosmic king sits on a throne decorated with bulls and vines, surrounded by his flourishing domain. He holds a scepter and pentacle with easy confidence. His castle and gardens show his success. Wealth, business acumen, and security. " + PENTACLES_STYLE }
];

export const TAROT_PROMPTS = [
  ...MAJOR_ARCANA_PROMPTS,
  ...WANDS_PROMPTS,
  ...CUPS_PROMPTS,
  ...SWORDS_PROMPTS,
  ...PENTACLES_PROMPTS
];